### ISSUE TITLE
Undocumented dependencies

### ISSUE THREAD

**Issue by dmjacobson** [fsmMLK/inkscapeLogicGates#2]
It seems that inkscapeLogicGates requires the following items that, to my knowledge, are not mentioned in the installation instructions.  FWIW I'm using Ubuntu 16.04.

pygtk
Tkinter
pdf2svg
pstoedit

**Comment by fsmMLK** [comment]
These are required by textext. You will need them only if you want to have latex support. I will include this info in the installation instructions. 

tks.

**Comment by fsmMLK** [comment]
anyway I will fork textext in the near future so that you don't need pygtk and tkinter.

**Comment by fsmMLK** [comment]
Added this information in the inkscapeMadeEasy’s installation section.
