### ISSUE TITLE
Logic gates became unresponsive

### ISSUE THREAD

**Issue by dmjacobson** [fsmMLK/inkscapeLogicGates#3]
I was working on a schematic diagram..   I had been using inkscapeLogicGates for a couple of hours.  At the moment of the malfunction I'm reporting I was zoomed way in, and the Logic Gates window was not being displayed. I clicked on Extensions->fsmMLK->Circuit Symbols->Logic Gates...  .  Nothing happened.  I tried 3 or 4 times, and still nothing happened.   I saved my work, exited Inkscape, restarted Inkscape, and opened the file I had been working on, and all worked fine.

Of course, this could have been a bug in Inkscape or even below.  But I'm reporting it for the record.

Here is the info on the environment
Inkscape 0.91.r13725
Running on Ubuntu Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
Memory 8.3 GB
Intel Core i-56300U CPU @2.40Ghz X 2
Graphics: Gallium 0.4 on SVGA3D; build: RELEASE; LLVM
OS type 64-bit
Disk 11.9GB
That was running on VMware Workstation 12 Pro 12.5.7 build-5813279
Memory 20300 MB
HOST OS Windows 10, 64-bit  (Build 14393) 10.0.14393
And Windows reports:
Windows 10 Enterprise
Processor Intel Core i5-6300U CPU @2.40 GHz 2.50 GHz
Installed RAM 20.0 G  (19.8 usable)
System type: 64-bit Operating System x64-based processor
Computer Lenovo T460s

**Comment by fsmMLK** [comment]
It seems like an inkscape bug. Keep me informed if this issue occurs again.
