### ISSUE TITLE
Unrecoverable error in gs

### ISSUE THREAD

**Issue by dmjacobson** [fsmMLK/inkscapeLogicGates#4]
When I try to create a flip flop, I get a failure,

I am using that last version of inksapeLogicGates and inkscapeMadeEasy in  Inkscape 0.92.3 (2405546, 2018-03-11).  

I am running on Ubuntu 16.04 (?), which is a virtual machine on a Windows 10 laptop, using VMware Workstation 14.1.3 build-9474260.

 $ uname -a
Linux ubuntu 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linuxi

The traceback is below.

Thank you,
   --David

Traceback (most recent call last):
  File "logicGates.py", line 681, in <module>
    logic.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "logicGates.py", line 121, in effect
    asynPreset=int(so.latchPreset),asynClear=int(so.latchClear),size=so.latchSize,suppressq=so.latchSuppressq, suppressNOTq=so.latchSuppressNOTq)
  File "logicGates.py", line 632, in createLatch
    self.createOutput(True,group,position=[x_max,position[1]-dist_signal],extraLength=0.0,label='Q',name='$Q$',fontSizeFactor=fontSizeFactorG)
  File "logicGates.py", line 265, in createOutput
    self.createSignal(flagTrue,parent,[position[0],position[1]],direction,extraLength,label,name,fontSizeFactor)
  File "logicGates.py", line 233, in createSignal
    inkDraw.text.latex(self,group,name,position=posText,fontSize=self.fontSize*fontSizeFactor,refPoint=justif,preambleFile=self.preambleFile)
  File "/usr/share/inkscape/extensions/inkscapeMadeEasy_Draw.py", line 1230, in latex
    tex.affect([r'--text=' + LatexCommands + LaTeXtext, '--scale-factor=1', '--preamble-file=' + preambleFile, tempFilePath], output=False)
  File "/usr/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "/usr/share/inkscape/extensions/textextLib/textext.py", line 151, in effect
    self.options.scale_factor, converter_cls, old_node)
  File "/usr/share/inkscape/extensions/textextLib/textext.py", line 165, in do_convert
    new_node = converter.convert(text, preamble_file, scale_factor)
  File "/usr/share/inkscape/extensions/textextLib/textext.py", line 533, in convert
    self.pdf_to_svg()
  File "/usr/share/inkscape/extensions/textextLib/textext.py", line 631, in pdf_to_svg
    + pstoeditOpts)
  File "/usr/share/inkscape/extensions/textextLib/textext.py", line 374, in exec_command
    % (' '.join(cmd), p.returncode, out + err))
RuntimeError: Command pstoedit -f plot-svg /tmp/tmpJfXvcd/tmp.pdf /tmp/tmpJfXvcd/tmp.svg -dt -ssp -psarg -r9600x9600 failed (code 1): pstoedit: version 3.70 / DLL interface 108 (built: Aug 29 2017 - release build - g++ 7.2.0 - 64-bit) : Copyright (C) 1993 - 2014 Wolfgang Glunz

 *** WARNING - the DELAYBIND command has been deprecated, and will be
               removed in the next version. For now you can restore
               the behaviour by using -dREALLYDEALYBIND but if you
               require continued use of this command you should contact
               the Ghostscript developers. Commercial customers of
               Artifex should email their support contact, free users
               are encouraged to talk to us on the #ghostscript IRC
               channel on irc.freenode.net.

Unrecoverable error: undefined in DELAYBIND
PostScript/PDF Interpreter finished. Return status 65280 executed command : /usr/bin/gs -q -dDELAYBIND -dWRITESYSTEMDICT -dNODISPLAY -dNOEPS -r9600x9600 "/tmp/psin7W0MOt"
The interpreter seems to have failed, cannot proceed !

**Comment by fsmMLK** [comment]
This is a known and rather new issue between pstoedit and ghostscript. In my machine (kubuntu 18.04) the current versions of pstoedit (3.70) and ghostscript (9.22) will present this issue.

In my case, the solution was to download gs v.9.23 source and install it manually. For instructions, please follow answer #2 by jcwinkler, in Jun 13 at 11:30 in the link below.
https://askubuntu.com/questions/1034894/render-latex-is-not-working-in-inkscape-after-installing-to-18-04

keep in mind that future apt-get updates might overwrite your ghostscript changes. You might have to repeat this process if you start to see these error messages again.

cheers

Ps:  I think the most recent version of gs you can download from gs website today is 9.25. I did not test the compatibility with 9.25. The version 9.23 works fine in my machine. You can find older versions in this link
https://github.com/ArtifexSoftware/ghostpdl-downloads/releases

**Comment by dmjacobson** [comment]
All I could find at https://www.ghostscript.com/download/gsdnld.html was version 9.25.  I move /usr/bin/gs aside and copied version 9.25 in its place.  It seemed to work fine.  But I have only used it so for on one small test case.

**Comment by fsmMLK** [comment]
You can find older versions at https://github.com/ArtifexSoftware/ghostpdl-downloads/releases, but if 9.25 works for you, then you are good to go. =)

If the extension can create  a simple boolean expression (signals & expressions TAB) with adequate LaTeX text, you should be fine.

**Comment by fsmMLK** [comment]
UPDATE:

Today (oct/1st/18) ghostcript 9.25~dfsg+1-0ubuntu0.18.04.1 package was officially released for kubuntu 18.04. You can install it using the usual apt-get update/upgrade

This version seems to solve the  pstoedit<-> gs  issue.
