### ISSUE TITLE
scale difference between logic and transistors

### ISSUE THREAD

**Issue by danmcmahill** [fsmMLK/inkscapeLogicGates#7]
Thanks for all the work making a good looking symbol generator.  I do have a few suggestions though.  The scale factor between things like transistors and logic gates seems off.  For example the flip-flop in this drawing is 12 grid sizes tall compared to 2 for the NMOS (6x the height) and the width is 10 vs about 2 (5x).  

![image](https://user-images.githubusercontent.com/22477431/134982607-84ccb2f2-8287-4ec9-98a9-8ed043056b57.png)

What is more typical (this is from a fairly representative set of symbols in a high end EDA tool) is something like this:
![image](https://user-images.githubusercontent.com/22477431/134983143-fe7cdd32-4969-4043-bccb-f92b535b9a6c.png)
In this case the flip-flip is about 3x the height and a little over 2x the width.  In terms of area used on the drawing, that puts the inkscape one at about 30x the area used for a flip-flop than an NMOS and about 6x in the example above.  That is pretty huge as even a small amount of logic can totally dwarf the transistors.

**Comment by fsmMLK** [comment]
done! check if sizes are ok.
