### ISSUE TITLE
Error when trying logicgates

### ISSUE THREAD

**Issue by JorgeMarinN** [fsmMLK/inkscapeLogicGates#8]
Hello,
I'm trying to use the extension but I get the following error when clicking in the inkscape menu:

usage: logicGates.py [-h] [--output OUTPUT] [--id IDS]
                     [--selected-nodes SELECTED_NODES] [--tab TAB]
                     [--subTab_sigExp SUBTAB_SIGEXP] [--ANDgate ANDGATE]
                     [--ORgate ORGATE] [--XORgate XORGATE] [--NOTgate NOTGATE]
                     [--BUFgate BUFGATE] [--NANDgate NANDGATE]
                     [--NORgate NORGATE] [--XNORgate XNORGATE]
                     [--nInput NINPUT] [--InputTypes INPUTTYPES]
                     [--latchType LATCHTYPE] [--latchSize LATCHSIZE]
                     [--latchSuppressq LATCHSUPPRESSQ]
                     [--latchSuppressNOTq LATCHSUPPRESSNOTQ]
                     [--latchGate LATCHGATE] [--latchGateLogic LATCHGATELOGIC]
                     [--latchPreset LATCHPRESET] [--latchClear LATCHCLEAR]
                     [--signal SIGNAL] [--signalVal SIGNALVAL]
                     [--signalRot SIGNALROT] [--signalDrawLine SIGNALDRAWLINE]
                     [--boolExpression BOOLEXPRESSION]
                     [INPUT_FILE]
logicGates.py: error: argument INPUT_FILE: File not found: /home/fernando/servidor/UFABC/02_DISCIPLINAS/000_simbolosEletricos_1.0.svg

I can't find the "000_simbolosEletricos_1.0.svg". Any idea what could I be doing wrongly?
Thanks in advance.

Jorge

**Comment by fsmMLK** [comment]
There was a small bug in my code. Please download the .py file again.

Thanks for letting me know about this stupid error =)

**Comment by JorgeMarinN** [comment]
It works now, thanks so much!
